local hop = require('hop')
vim.keymap.set('', '<leader>w', function()
  hop.hint_words({})
end, {remap=true})
-- vim.keymap.set('', '<leader>l', function()
--   hop.hint_lines({})
-- end, {remap=true})
-- vim.keymap.set('', '<leader>;', function()
--   hop.hint_anywhere({})
-- end, {remap=true})
